### ISSUE TITLE
Binary file cannot be executed on MacOS

### ISSUE THREAD

**Issue by antoncoding** [OptimizorClub/sqrt_foundry_template#3]
While running `forge test --use ./bin/solc`, I ran into this error 
```
Error: ./bin/solc: cannot execute binary file
```
After some googling, it seems like it's because of non-compatible binary file. (I'm running it on Macbook M1 chip.) 
```shell
# info on the binary
$ file ./bin/solc
./bin/solc: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0

# info on local machine
$uname -mp
x86_64 i386
```
I would be nice if the team can you provide binary file to execute solidity 0.8.18 on machines other than Linux, or some more detailed guide around how to build 0.8.18 locally.

**Comment by leonardoalt** [comment]
Yea true.
@axic can you upload your macos binary here?

**Comment by leonardoalt** [comment]
@antoncoding can you try this binary instead: https://output.circle-artifacts.com/output/job/f2a31866-e2c1-4dfa-a940-82c5db9cd012/artifacts/0/solc
this is directly from the Solidity OSX CI

**Comment by antoncoding** [comment]
It works! I did need to change the pragma to `^0.8.17` because this non-stable version is considered lower than 0.8.18.

**Comment by pradyuman-verma** [comment]
@leonardoalt @antoncoding 
Replacing above shared binary with `./bin/solc` gives this error on `forge test --use ./bin/solc`
```js
[⠊] Compiling...
Error:
"./bin/solc": Permission denied (os error 13)
```

**Comment by skyonedot** [comment]
> @leonardoalt @antoncoding Replacing above shared binary in `./bin/solc` throws this error on `forge test --use ./bin/solc`
> 
> ```js
> [⠊] Compiling...
> Error:
> "./bin/solc": Permission denied (os error 13)
> ```

chmod 777 ./bin/solc

**Comment by pradyuman-verma** [comment]
> > @leonardoalt @antoncoding Replacing above shared binary in `./bin/solc` throws this error on `forge test --use ./bin/solc`
> > ```js
> > [⠊] Compiling...
> > Error:
> > "./bin/solc": Permission denied (os error 13)
> > ```
> 
> chmod 777 ./bin/solc

Thanks, but how to bypass this 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/63545809/199223062-50d9cea2-6976-4398-8d4f-4c5113bbb39d.png">

**Comment by leonardoalt** [comment]
I have no idea. You have to tell your OSX to accept it somehow.

**Comment by pradyuman-verma** [comment]
> I have no idea. You have to tell your OSX to accept it somehow.

Found this - https://github.com/OptimizorClub/sqrt_foundry_template/issues/3#issuecomment-1298325657

**Comment by skyonedot** [comment]
> 

`system preference` >> `security and privacy`

then you will see the `solc`.

just accpet it

**Comment by nicobevilacqua** [comment]
Hi, I had this same issue and after I downloaded the solc version for my M1 mac and added the access permissions to the I get this error now.

`When the parameter "appendCBOR" is set to false, the parameter "bytecodeHash" cannot be set to "ipfs". The parameter "bytecodeHash" should either be skipped, or set to "none".`

Any idea?

**Comment by nicobevilacqua** [comment]
Ok, I figured out. I had to add **bytecode_hash = "none"** to my foundry.toml file

```toml
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
    'forge-std=lib/forge-std/src/',
]

solc = '0.8.18'
cbor_metadata = false
bytecode_hash = "none"
```
