### ISSUE TITLE
purityChecker Falsed

### ISSUE THREAD

**Issue by skyonedot** [OptimizorClub/sqrt_foundry_template#4]
Hi, I succeeded in finding the square root, and within the error margin

But when I test it, `MySolutionTest::testEndToEnd` keeps giving me an error

What could be the reason?

![image](https://user-images.githubusercontent.com/49084147/198896295-88988175-c452-4308-b919-80ded6d06dae.png)

**Comment by skyonedot** [comment]
And I also deploy my solution contract `https://etherscan.io/address/0x50c231dcf77f66875b92cc2e1fe6bc55ec12ed5f`,

it work well in SQRT Contract

![image](https://user-images.githubusercontent.com/49084147/198896626-8cb8048e-a49e-4cec-9ca4-e3fdbdfa8f6b.png)

but it really can't pass the test

**Comment by skyonedot** [comment]
I am stuck in the `purityChecker` 
My contracts are all return false... I don't know how to correct it
![image](https://user-images.githubusercontent.com/49084147/198959250-a1988136-8c22-4ab3-a8ae-22f886d507d8.png)

**Comment by leonardoalt** [comment]
The error 0x45280b8a in the end to end test says that you haven't submitted the codehash, or submitted the wrong one. Note that when you `commit`, the given address must be the same as the `msg.sender` of `challenge`.

**Comment by leonardoalt** [comment]
If you're writing Solidity code, you need to remove the metadata hash from the bytecode. Are you running `$ forge test --use ./bin/solc`?

**Comment by skyonedot** [comment]
> If you're writing Solidity code, you need to remove the metadata hash from the bytecode. Are you running `$ forge test --use ./bin/solc`?

yeah, i had running `$ forge test --use ./bin/solc`\

what should i do to remove the metadata hash from the bytecode.?

**Comment by skyonedot** [comment]
$ forge test --use ./bin/solc

![image](https://user-images.githubusercontent.com/49084147/198992313-e0ac7784-90d6-4183-80b1-fc943d560563.png)

**Comment by leonardoalt** [comment]
> what should i do to remove the metadata hash from the bytecode.?

The default foundry profile should already do that if you're using that solc binary.

**Comment by skyonedot** [comment]
> > what should i do to remove the metadata hash from the bytecode.?
> 
> The default foundry profile should already do that if you're using that solc binary.

yes, i also agree.

and i use `forge create --rpc-url $RPC  --private-key $PRIV src/MySolution.sol:MySolution --use ./bin/solc` to deploy my contract,  is it right?

**Comment by leonardoalt** [comment]
yea that should do it.

Can you add an rpc_url test that uses the deployed PurityChecker?

**Comment by skyonedot** [comment]
> yea that should do it.
> 
> Can you add an rpc_url test that uses the deployed PurityChecker?


this?

![image](https://user-images.githubusercontent.com/49084147/198995163-181a984f-bca1-4712-bef9-96259fcf5bb8.png)

`that uses the deployed PurityChecker?` 👀 i can't understand

**Comment by skyonedot** [comment]
do you mind that  I send you my solution code to you via twitter message or mail , 👀

**Comment by skyonedot** [comment]
Or can you send me an example contract code that passes the `purityChecker` check?

**i had try to fork mainnet by latest block and debug localhost.**

- I tried the Contract template that was given, nothing changed.  and deploy it by `forge create --rpc-url http://127.0.0.1:8545 --private-key $PRI src/MySolution.sol:MySolution --use ./bin/solc`

  then i get deployed contract address,  i try to call `purityChecker` contract `check` function, it return `false`

  > https://etherscan.io/address/0x5C71fcd090948dCC5E8A1a01ad8Fa26313422022#readContract

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.18;

import {ISqrt, INPUT_SIZE} from "src/SqrtChallenge.sol";
import {Fixed18} from "src/Fixed18.sol";

contract MySolution is ISqrt {
    function sqrt(Fixed18[INPUT_SIZE] calldata input) external pure returns (Fixed18[INPUT_SIZE] memory output) {
        for (uint256 i = 0; i < input.length; ++i) {
            output[i] = input[i];
        }
    }
}
```



- and then i try a simple contract. it also can't pass the `purityChecker` contract `check` function

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract CheckPure {
    constructor(){}
    function computeKey() external pure  {
    }
}
```





![image](https://user-images.githubusercontent.com/49084147/199007129-0dc0ef7a-e7e9-49cd-ba25-aeef60affb81.png)

**Comment by skyonedot** [comment]
Great, i have to say the foundry is so great,, Nice Tool,
i run the provided example solution and nothing changed, just want to test the `purity check` `isPureGlobal`
 but it was wrong obviously,,  
do you succeed in the `purity check` run the example?

![image](https://user-images.githubusercontent.com/49084147/199138570-0f81325f-5b2c-404e-8a8f-ccdfcad82966.png)

**Comment by skyonedot** [comment]
Well.. I use my friends' mac, the same code, it passed the `purity check`
> maybe it is solc version or something

but it seem too difficult to submit, because someone had make it `4000` gas to calculate square root..

i have to say optimizor is so great activity.  
thanks, very much

**Comment by skyonedot** [comment]
https://etherscan.io/address/0xfd8e46f80ec8a2f05732b58744921fa8234c4a6b

This man is very, very smart

It's just, he seems to have messed up the rules... 
Took almost all of the NFT.
his submit is not work 100%.

**Comment by skyonedot** [comment]
I know how he does it.

`Because block.difficulty is 1 most of the time`
So just write the answer and return it...

As shown in the picture
![image](https://user-images.githubusercontent.com/49084147/199200212-ea44b398-c68c-4ff3-9928-3b930c3ef42e.png)


> maybe the random numbers should not be used with block.difficulty
> chainlink maybe better ❤️

**Comment by leonardoalt** [comment]
That's not true. `block.difficulty` is `prevrandao` since the merge. If you could predict the input numbers the gas consumption would be a lot lower than the current leader.

In any case, is the purity checker working now? Did you run the test I suggest in my previous comment?

**Comment by skyonedot** [comment]
yeah, , the purity checker only working in my mac computer, but it is not work in my ubuntu server (20.04). both of them have same code ..
> i think maybe there is something wrong about solc or something.

--- 
well.. i think it is so amazing that calculate square root just cost `4364` gas..  
> can't imagine😂

the current leader is `0xF3F99Ab03D1371626a86A7ea7C02128349eF62dD`
it is not work for all seed, when the seed it 1,5,6 it is not passed
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/49084147/199229509-c63318b9-e082-4c2a-ae60-3f03e51963bc.png">


and it passed when the seed it 2,3,4

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/49084147/199229600-c29c4eb5-221f-4ff5-ae54-69a796822f65.png">

---

Ideally, they should all pass

**Comment by skyonedot** [comment]
I use specific seed ant just return the specific number with no logic,, the gas cost is `4911`
![](https://user-images.githubusercontent.com/49084147/199200212-ea44b398-c68c-4ff3-9928-3b930c3ef42e.png)
